# Migration Assessor Configuration
[project]
source = "C:/Users/16017/AppData/Local/Temp/eve_clone_io5fuc3d.4nf"
source_lang = "typescript"
target_language = "rust"
source_version = "f44e16a3e5da03e11b1674c1ab041f5cc0941297"

[skip]
framework = false
