# Migration Assessor Configuration
[project]
source = "C:/Users/16017/Documents/AI/migration-assessor/e2e-full/../ts-ecommerce"
source_lang = "typescript"
target_language = "rust"
source_version = "c5ff909"
target = "../rust-ecommerce"

[skip]
framework = false
